### PR TITLE
update project funding tab

### PR DESCRIPTION
**Pull request by M-Rb3**

### CODE REVIEW

**Comment by lachlanglen** [comment]
@M-Rb3 please add a summary so I know what I'm looking at here - thanks

**Comment by M-Rb3** [comment]
@lachlanglen  
- updated the Funding Raised tab to show the donations sent to the project. currently, it shows direct donations and matching round donations. I was not sure about how the payout object will be so I left it out for now
image

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Thanks @M-Rb3 

I made a couple small updates, please make sure to pull these before adding your changes.

It all looks good and works well on desktop; can you update the Donations table for mobile responsiveness, so you don't have to scroll horizontally to view the table entries?

Currently on mobile:
Screenshot 2024-02-21 at 9 49 29 AM

**Comment by M-Rb3** [comment]
@lachlanglen 
image

**Review by lachlanglen — APPROVED** [review]
looks great, thank you

**Pull request merged**
