### PR TITLE
Feat/proj-v2

### PR DESCRIPTION
**Pull request by M-Rb3**
closes [#418](https://github.com/PotLock/bos-app/issues/418)
closes [#417](https://github.com/PotLock/bos-app/issues/417)
closes [#416](https://github.com/PotLock/bos-app/issues/416)
closes [#415](https://github.com/PotLock/bos-app/issues/415)

smart contracts, external funding, potlock funding
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=fradao.sputnik-dao.near&nav=home

external funding
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=nearhacks.near&nav=funding

no fudning 
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=nftclub_eduhub.near&nav=funding

GitHub URLs
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=near-social-bridge.near&nav=home

Potlock Funding
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=yearofchef.near&nav=funding

No pots
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=potlock.near&nav=pots

pots
http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=yearofchef.near&nav=pots

### CODE REVIEW

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Looking good! Some notes:

**HEADER**

1. Should display "Verified" next to avatar if project is approved. If project is not approved, followers/following text should be situated next to avatar. (right now some projects show "verified" and others don't, not sure why this is)
Screenshot 2024-03-10 at 7 49 56 PM

2. Not enough gap between followers/following count & "followers"/"following" text (designs give 8px gap)
Screenshot 2024-03-10 at 7 49 56 PM

3. Need some gap between total amount raised & "raised from N donors" text (I know there's none in the design but it looks weird - use your judgement)
Screenshot 2024-03-10 at 7 53 03 PM

4. "Dao" tag should be uppercase, "DAO"
Screenshot 2024-03-10 at 7 53 59 PM

5. Link icon is the wrong icon to use here, it should be a copy icon like next to the smart contract addresses
Screenshot 2024-03-10 at 7 53 59 PM

Screenshot 2024-03-10 at 7 54 42 PM

6. When you hover over the "Following" button can the text change to "Unfollow?"

7. Some avatars displaying incorrectly, e.g. http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=daoashe.near
Screenshot 2024-03-10 at 8 07 51 PM


**HOME**

Nothing to say except I love the hover effect on team members avatars!

**SOCIAL FEED**
8. If the project has [no social feed](http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=fradao.sputnik-dao.near&nav=home), nothing displays. Should display something like "No posts to display" or it looks like there was an error or it's not implemented

**FUNDING RAISED**
9. Count badge/pill doesn't display as per designs
Screenshot 2024-03-10 at 7 59 16 PM

10. filter menu items not consistently capitalized/pluralized. Should be as follows:
All donations
Direct donations
Matched donations
Matching pool allocations
Screenshot 2024-03-10 at 8 00 15 PM

11. Filter menu should hide when user clicks outside the menu

12. Typo (should be "Direct donation" not "Direct Donatio")
Screenshot 2024-03-10 at 8 01 37 PM

**Comment by M-Rb3** [comment]
@lachlanglen 
- the  Count badge/pill is not displayed as per designs, it does not look good with a big number of more than 3 digits that's why I did not add it
- the social feed no prop can be passed to handle this, I ended up forking over the whole thing, and I asked Emmanuel for a design, it still does not look, and to match the other tabs. I will add it when he finishes it

**Comment by M-Rb3** [comment]
closes [#432](https://github.com/PotLock/bos-app/issues/432)

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Thanks! Looking good.

1. Sorry, I was confused about the copy/link icon on the profile header. It looks good now but rather than copying the referral link, it should copy the account address (the referral link will live somewhere else and say "Earn referral fees")
Screenshot 2024-03-11 at 6 55 52 PM

2. Change this text to "This project has not posted yet" rather than "The project has not posted yet"
Screenshot 2024-03-11 at 7 00 13 PM

3. Donations count pill still not displaying correctly (needs background)
Current:
Screenshot 2024-03-11 at 7 01 08 PM

Design:
Screenshot 2024-03-11 at 7 01 30 PM

4. Incorrect font size for total raised amount on mobile (2.5rem, should be 32px on mobile)
Screenshot 2024-03-11 at 7 38 54 PM

5. Selected tab should be within view on mobile
Screenshot 2024-03-11 at 7 50 24 PM

6. I think funding source amounts should align to NEAR icon rather than aligning the amount to the right edge, otherwise it looks wonky
Screenshot 2024-03-11 at 7 44 35 PM

7. "Sort amount" doesn't work (these should be sorted in descending order of amount)
Screenshot 2024-03-11 at 7 47 02 PM

8. "Sort Date" doesn't work - seems to be sorting by amount instead?
Screenshot 2024-03-11 at 7 47 37 PM

**I know this isn't clear in the designs, but for both these sort options, the arrow should only display if that is the option that is selected. E.g. the default view should be by date reverse chronologically, so that arrow should be visible and down by default. If I tap on "Sort Date", the arrow should change to up. If I tap on "Sort Amount", the "Sort Date" arrow should disappear and the "Sort Amount arrow should appear instead.**

9. Getting various errors on `?tab=profile` view, e.g. http://127.0.0.1:8080/potlock.near/widget/Index?tab=profile&accountId=lachlan.near
Screenshot 2024-03-11 at 7 51 48 PM

10. "Replace is not a function" when viewing some project profiles e.g. http://127.0.0.1:8080/potlock.near/widget/Index?tab=project&projectId=magicbuild.near
Screenshot 2024-03-11 at 7 56 36 PM

10. Replace "Loading" text on profile with skeleton

11. Replace `?` with `-` here (while loading followers stats)
Screenshot 2024-03-11 at 7 57 53 PM

**Review by lachlanglen — APPROVED** [review]
excellent work, thank you!

**Pull request merged**
