### PR TITLE
fix:  Project Cards Cutoff on Right Side for Explore page

### PR DESCRIPTION
**Pull request by louisdevzz**

### CODE REVIEW

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Can you make sure the width doesn't exceed 100vw? cards should be centered but it shouldn't scroll horizontally on mobile (see screen recording)

https://github.com/PotLock/bos-app/assets/54282009/da3ed0fe-2b64-46dc-9531-e308d5102353

**Comment by louisdevzz** [comment]
I can't see this bug. You can see this video
https://github.com/PotLock/bos-app/assets/112561517/d7164af2-0ed0-422c-b864-27dbe1798b81

**Comment by louisdevzz** [comment]
I tested and I don't see this bug in project

**Comment by lachlanglen** [comment]
Closing as this has been fixed by https://github.com/PotLock/bos-app/pull/364

**Pull request closed without merging**
