### PR TITLE
fix: Add search/filter back in to ListSection

### PR DESCRIPTION
**Pull request by louisdevzz**

### CODE REVIEW

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Thanks for opening this PR.

Search works, though it's a little slow fetching the social profile for every single project on every single keystroke in the search input. We can see how it goes but we may want to refactor this to fetch the social profiles at a higher level.

Right now the Sort filters don't appear to be working, so please look into that. Also, please display the currently selected Sort filter instead of the word "Sort" when a filter is applied. E.g. if I have selected the "Least to Most Donations" filter, the word "Sort" should be replaced by "Least to Most Donations".

Also, please use a `z-index` higher than `2` for the `FilterMenu` in `SearchBar.jsx`, as the background image on the profile card has a z-index of 2 and so the filter menu is being placed behind the background image currently (see screenshot)
Screenshot 2024-02-22 at 4 01 50 PM

**Review by lachlanglen — CHANGES_REQUESTED** [review]
When I run this branch, I don't see any search bar, and there are a lot of errors in console
Screenshot 2024-02-25 at 9 51 08 AM

**Comment by lachlanglen** [comment]
@louisdevzz I also merged in main, so please pull this branch again before making changes

**Comment by louisdevzz** [comment]
image
In my screen

**Comment by louisdevzz** [comment]
image
In my screen phone

**Review by lachlanglen — CHANGES_REQUESTED** [review]
When I load the projects page, 0 projects are displayed

Screenshot 2024-02-26 at 9 45 59 AM

**Comment by louisdevzz** [comment]
You need reload page that load all project

**Comment by lachlanglen** [comment]
> You need reload page that load all project

No it doesn't:

https://github.com/PotLock/bos-app/assets/54282009/5e493f37-140e-4f5f-9277-580ca3f7f872

**Comment by lachlanglen** [comment]
Thanks, I commented out the "amount"-based sort filters because they aren't working, but the rest looks good.

**Review by lachlanglen — APPROVED** [review]
Commented out amount-based sort filters because they aren't working, but the rest looks good

**Pull request merged**
