### PR TITLE
Improve Shopping Cart

### PR DESCRIPTION
**Pull request by elliotBraem**
_Resolves #304_

## Regression

- [x] Number of items increments in cart when item is added to it
- [x] Number of items decrements in cart when item is removed
- [x] Option to Add or Remove from cart dependent on existence in cart
- [x] Clicking "Cart" brings up Donation Cart Modal
- [x] Donation Modal shows all items in cart
- [x] Donation Modal Checkout Item can be removed clicking trashcan icon
- [x] Proceed to donate navigates to checkout page
- [x] Items in donation cart all show on checkout page
- [x] Item can be removed from donation cart on checkout page
- [x] Multiple Items can be removed from donation cart on checkout page
- [x] Modifying amount or currency updates item in cart
- [x] Items in cart are associated with their Pot
- [x] Successful donation clears cart

### Add/remove from cart, much smoother now, video not sped up.

add-remove-potlock-cart

### CODE REVIEW

**Review by lachlanglen — CHANGES_REQUESTED** [review]
Thanks for the PR @elliotBraem, definitely a big improvement.

Can you just add functionality to open the cart modal when an item is added? Otherwise it's not clear that you've added the item to your cart.

Please pull the latest changes first, as I made some updates (the complete removal of `State` from `Index.jsx` broke much of the success handling logic)

Thank you!

**Comment by lachlanglen** [comment]
Also this error appears to be introduced in this PR and I get it a lot:
Screenshot 2024-03-20 at 11 53 08 AM

It's definitely coming from `Components.Nav` somehow, as when I comment out [this line](https://github.com/PotLock/bos-app/blob/5788f1784ce210d5373d6d01ceef6cf43d015d5d/apps/potlock/widget/Index.jsx#L160) it does not occur. But I couldn't figure out exactly where in `Nav` it is being triggered.

**Comment by elliotBraem** [comment]
@lachlanglen Regarding these errors, I've opened up an issue in bos-workspace repo. I believe it is poor latency for local development -- I think we are attempting with the published component before loading the local one -- turning off wifi makes the errors go away (full local)

I'm working on the cart open on donate now

**Review by lachlanglen — APPROVED** [review]
looks good, thanks

**Pull request merged**
